"use strict";

const express = require("express");
const router = express.Router();
const authRoutes = require("./auth");
const userRoutes = require("./users");
const departmentRoutes = require("./departments");
const researchCenterRoutes = require("./researchCenters");
const submissionRoutes = require("./submissions");
const leaveRoutes = require("./leaves");
const portfolioRoutes = require("./portfolio");
const qualificationRoutes = require("./qualifications");
const publicationRoutes = require("./publications");
const conferenceRoutes = require("./conferences");
const patentRoutes = require("./patents");
const workshopRoutes = require("./workshops");
const membershipRoutes = require("./memberships");
const scholarshipRoutes = require("./scholarships");
const projectRoutes = require("./projects");
const grantRoutes = require("./grants");
const guidanceRoutes = require("./guidance");
const awardRoutes = require("./awards");
const consultancyRoutes = require("./consultancy");
const resourcePersonRoutes = require("./resourcePerson");
const collaborationRoutes = require("./collaborations");
const scholarProgressRoutes = require("./scholarProgress");
const profileRoutes = require("./profile");
const incentiveRoutes = require("./incentives");
const reportRoutes = require("./reports");
const settingsRoutes = require("./settings");
const uploadRoutes = require("./uploads");
const healthRoutes = require("./health");
const researchGuidesRoutes = require("./researchGuides");
const submissionController = require("../controllers/submissionController");
// Mount sub-routes under their respective prefixes
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/research-guides", researchGuidesRoutes);
router.use("/departments", departmentRoutes);
router.use("/research-centers", researchCenterRoutes);
router.use("/research-centres", researchCenterRoutes);
router.use("/submissions", submissionRoutes);
router.use("/leaves", leaveRoutes);
router.use("/portfolio", portfolioRoutes);
router.use("/qualifications", qualificationRoutes);
router.use("/publications", publicationRoutes);
router.use("/conferences", conferenceRoutes);
router.use("/patents", patentRoutes);
router.use("/workshops", workshopRoutes);
router.use("/memberships", membershipRoutes);
router.use("/scholarships", scholarshipRoutes);
router.use("/projects", projectRoutes);
router.use("/grants", grantRoutes);
router.use("/guidance", guidanceRoutes);
router.use("/awards", awardRoutes);
router.use("/consultancy", consultancyRoutes);
// Support both URL patterns (kebab-case and camelCase)
router.use("/resource-person", resourcePersonRoutes);
router.use("/resourcePerson", resourcePersonRoutes);
router.use("/collaborations", collaborationRoutes);
router.use("/scholar-progress", scholarProgressRoutes);
router.use("/scholarProgress", scholarProgressRoutes);
router.use("/profile", profileRoutes);
router.use("/incentives", incentiveRoutes);
router.use("/reports", reportRoutes);
router.use("/settings", settingsRoutes);
router.use("/uploads", uploadRoutes);
router.use("/health", healthRoutes);
// Directly map submission status checks for approvals report
router.get("/approvals", submissionController.getAll);
module.exports = router;
